---
- name: advanced template test
  hosts: all
  tasks:
  - name: template vhost file
    template:
      src: advanced_template.j2
      dest: /home/ansible/advanced_template.out
      owner: ansible
      group: ansible
      mode: 0644
