---
- hosts: all
  tasks:
    - block:
      - yum:
          name: httpd
          state: installed
      when: ansible_os_family == 'RedHat'
      become: yes

    - block:
      - apt:
          name: apache2
          state: installed
      when: ansible_os_family == 'Debian'
      become: yes
