---
- name: Install vsftpd on Red Hat webservers != "7"
  hosts: host*.example.com
  become: yes
  tasks:
    - name: Install FTP server when host in webserver group
      yum:
        name: vsftpd
        state: latest
      when:
        inventory_hostname in groups["webserver"] and ansible_distribution == "RedHat" and ansible_distribution_major_version != "7"
