---
# tasks file for roles/apache_vhost
- name: install httpd
  yum:
    name: httpd
    state: latest
- name: start and enable httpd service
  service:
    name: httpd
    state: started
    enabled: true
- name: Open port 80
  firewalld:
    service: httpd
    permantent: true
    state: enabled
    immediate: yes
- name: deliver html content
  copy:
    src: html/
    dest: "/var/www/vhosts/{{ ansible_hostname }}"

- name: template vhost file
  template:
    src: vhost.conf.j2
    dest: /etc/httpd/conf.d/vhost.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart_httpd
